backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projets"
    label: "Projets"
    folder: "projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Lien", name: "link", widget: "string" }
